display_name: TuTu4kA VPN
publisher_display_name: Ihgap
identity_name: Ihgap.TuTu4kAVPN
msix_version: 4.1.2.0
logo_path: windows\runner\resources\app_icon.ico
capabilities: internetClient, internetClientServer, privateNetworkClientServer
languages: en-us, ru-ru
protocol_activation: hiddify
execution_alias: tutu4ka
certificate_path: windows\sign.pfx
certificate_password:
publisher: CN=8CB43675-F44B-4AA5-9372-E8727781BDC4
install_certificate: "false"
enable_at_startup: "true"
startup_task:
  parameters: --autostart

# For testing with a self-signed certificate
# publisher: CN=Hiddify-Test
# certificate_password: "1234"
# install_certificate: "true"
